from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/background.png"))
        self.label.setObjectName("label")
        self.un = QtWidgets.QLineEdit(self.centralwidget)
        self.un.setGeometry(QtCore.QRect(340, 210, 221, 31))
        self.un.setText("")
        self.un.setObjectName("un")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(238, 238, 236)")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.unlab = QtWidgets.QLabel(self.centralwidget)
        self.unlab.setGeometry(QtCore.QRect(240, 200, 111, 51))
        self.unlab.setStyleSheet("font-size:15pt; color:rgb(255, 255, 255)")
        self.unlab.setObjectName("unlab")
        self.uplab = QtWidgets.QLabel(self.centralwidget)
        self.uplab.setGeometry(QtCore.QRect(240, 250, 121, 51))
        self.uplab.setStyleSheet("font-size:15pt; color:rgb(255, 255, 255)")
        self.uplab.setObjectName("uplab")
        self.up = QtWidgets.QLineEdit(self.centralwidget)
        self.up.setGeometry(QtCore.QRect(340, 260, 221, 31))
        self.up.setText("")
        self.up.setObjectName("up")
        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(350, 370, 131, 41))
        self.loginbutton.setObjectName("loginbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHOME = QtWidgets.QAction(MainWindow)
        self.actionHOME.setObjectName("actionHOME")
        self.actionEXIT = QtWidgets.QAction(MainWindow)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuFILE.addAction(self.actionHOME)
        self.menuFILE.addAction(self.actionEXIT)
        self.menubar.addAction(self.menuFILE.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ADMIN LOGIN"))
        self.unlab.setText(_translate("MainWindow", "Username:"))
        self.uplab.setText(_translate("MainWindow", "Password:"))
        self.loginbutton.setText(_translate("MainWindow", "LOGIN"))
        self.menuFILE.setTitle(_translate("MainWindow", "FILE"))
        self.actionHOME.setText(_translate("MainWindow", "HOME"))
        self.actionEXIT.setText(_translate("MainWindow", "EXIT"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())