from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherLogin(object):
    def setupUi(self, TeacherLogin):
        TeacherLogin.setObjectName("TeacherLogin")
        TeacherLogin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TeacherLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/background.png"))
        self.label.setObjectName("label")
        self.un = QtWidgets.QLineEdit(self.centralwidget)
        self.un.setGeometry(QtCore.QRect(340, 210, 221, 31))
        self.un.setText("")
        self.un.setObjectName("un")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(250, 80, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color:rgb(238, 238, 236)")
        self.Title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Title.setLineWidth(1)
        self.Title.setWordWrap(False)
        self.Title.setObjectName("Title")
        self.unlab = QtWidgets.QLabel(self.centralwidget)
        self.unlab.setGeometry(QtCore.QRect(240, 200, 111, 51))
        self.unlab.setStyleSheet("font-size:15pt; color:rgb(255, 255, 255)")
        self.unlab.setObjectName("unlab")
        self.uplab = QtWidgets.QLabel(self.centralwidget)
        self.uplab.setGeometry(QtCore.QRect(240, 250, 121, 51))
        self.uplab.setStyleSheet("font-size:15pt; color:rgb(255, 255, 255)")
        self.uplab.setObjectName("uplab")
        self.up = QtWidgets.QLineEdit(self.centralwidget)
        self.up.setGeometry(QtCore.QRect(340, 260, 221, 31))
        self.up.setText("")
        self.up.setObjectName("up")
        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(360, 360, 131, 41))
        self.loginbutton.setObjectName("loginbutton")
        TeacherLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeacherLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        TeacherLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeacherLogin)
        self.statusbar.setObjectName("statusbar")
        TeacherLogin.setStatusBar(self.statusbar)
        self.actionHOME = QtWidgets.QAction(TeacherLogin)
        self.actionHOME.setObjectName("actionHOME")
        self.actionEXIT = QtWidgets.QAction(TeacherLogin)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuFILE.addAction(self.actionHOME)
        self.menuFILE.addAction(self.actionEXIT)
        self.menubar.addAction(self.menuFILE.menuAction())

        self.retranslateUi(TeacherLogin)
        QtCore.QMetaObject.connectSlotsByName(TeacherLogin)

    def retranslateUi(self, TeacherLogin):
        _translate = QtCore.QCoreApplication.translate
        TeacherLogin.setWindowTitle(_translate("TeacherLogin", "MainWindow"))
        self.Title.setText(_translate("TeacherLogin", "TEACHER LOGIN"))
        self.unlab.setText(_translate("TeacherLogin", "Username:"))
        self.uplab.setText(_translate("TeacherLogin", "Password:"))
        self.loginbutton.setText(_translate("TeacherLogin", "LOGIN"))
        self.menuFILE.setTitle(_translate("TeacherLogin", "FILE"))
        self.actionHOME.setText(_translate("TeacherLogin", "HOME"))
        self.actionEXIT.setText(_translate("TeacherLogin", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeacherLogin = QtWidgets.QMainWindow()
    ui = Ui_TeacherLogin()
    ui.setupUi(TeacherLogin)
    TeacherLogin.show()
    sys.exit(app.exec_())